name: Feature Suggestion
description: Suggest a new feature or enhancement for GovTool.
labels: ["Feature Request", "Needs UX Review"]
body:
  - type: markdown
    attributes:
      value:
        Please fill out the following details.
  - type: textarea
    id: problem-statement
    attributes:
      label: "💡 Feature Idea"
      description: "Please describe the user need, idea, or pain point."
      placeholder: "Example: Users struggle to find X functionality, leading to frustration and drop-off..."
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: "💡 Why is it needed?"
      description: "How would your new feature make things better?"
      placeholder: "Example: Users struggle to find X functionality, leading to frustration and drop-off..."
  validations:
      required: true
  - type: textarea
    id: user-impact
    attributes:
      label: "👥 Who is Impacted?"
      description: "Which users or personas will benefit from this feature? How does it improve their experience?"
      placeholder: "Example: This feature will help first-time users onboard faster..."
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: "🔗 Dependencies & Risks"
      description: "Does this feature affect existing workflows, integrations, or technical constraints?"
      placeholder: "Example: This feature depends on the authentication system update..."
    validations:
      required: false
  - type: textarea
    id: supporting-evidence
    attributes:
      label: "📊 Supporting Evidence (if any)"
      description: "Do you have any data, analytics, or user feedback supporting this request?"
      placeholder: "Example: 70% of surveyed users mentioned difficulty finding this feature..."
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: "⚡️ Priority Level"
      description: "How critical is this feature?"
      options:
        - "Low (Nice to Have)"
        - "Medium (Improves UX)"
        - "High (Critical to Users)"
    validations:
      required: true
  - type: checkboxes
    id: acknowledgments
    attributes:
      label: "☑️ Acknowledgments"
      description: "Please confirm you've reviewed our process before submitting."
      options:
        - label: "I have searched existing issues to avoid duplication."
          required: true
        - label: "I understand that this request will be evaluated and may not be implemented."
          required: true
