name: Add Issue to Projects

on:
  issues:
    types: [opened]

jobs:
  # https://github.com/actions/add-to-project
  add-to-project:
    name: Add issue and bugs to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/Ryun1/projects/1
          github-token: ${{ github.token }}