name: Update PR Description with Branch Link

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get the list of added files
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get the list of added files and store them in a temporary file
        gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files | map(select(.additions > 0)) | map(.path) | join("\n")' > added_files.txt

    - name: Debug - Show added files
      run: |
        echo "Added files:"
        cat added_files.txt

    - name: Get the PR details
      id: pr
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/${{ github.repository }}/pulls/${{ github.event.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update PR description
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      run: |
        REPO_NAME=${{ github.event.pull_request.head.repo.full_name }}
    - name: Clean up
      run: |
        rm -f added_files.txt