name: Update PR Description with Branch Link

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get the PR details
      id: pr
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/${{ github.repository }}/pulls/${{ github.event.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: List added files
      id: files
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/${{ github.repository }}/pulls/${{ github.event.number }}/files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update PR description
      run: |
        BRANCH_NAME=${{ github.event.pull_request.head.ref }}
        REPO_NAME=${{ github.event.pull_request.head.repo.full_name }}
        FILE_PATHS=$(jq -r '.files[] | select(.status == "added") | .filename' <<< "${{ steps.pr.outputs.files }}")

        # Prepare the links to the added files
        LINKS=""
        for FILE in $FILE_PATHS; do
          LINKS="$LINKS\n- [View file in branch](https://github.com/$REPO_NAME/blob/$BRANCH_NAME/$FILE)"
        done

        # Update the PR description
        gh pr edit ${{ github.event.pull_request.number }} --body "${{ github.event.pull_request.body }}\n\n### Links to Added Files:\n$LINKS"

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}