name: Update PR Description with Branch Link

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get the list of added files
      id: files
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files | map(select(.additions > 0)) | map(.path) | join("\n")')
        echo "files=$FILES" >> $GITHUB_ENV

    - name: Get the PR details
      id: pr
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/${{ github.repository }}/pulls/${{ github.event.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update PR description
      run: |
        BRANCH_NAME=${{ github.event.pull_request.head.ref }}
        REPO_NAME=${{ github.event.pull_request.head.repo.full_name }}

        # Prepare the links to the added files
        LINKS=""
        while IFS= read -r FILE; do
          LINKS="$LINKS\n- [View file in branch](https://github.com/$REPO_NAME/blob/$BRANCH_NAME/$FILE)"
        done <<< "${{ env.files }}"

        # Fetch the current PR description
        CURRENT_BODY=$(jq -r '.body' <<< "${{ steps.pr.outputs.data }}")

        # Append the new links to the current description
        UPDATED_BODY="$CURRENT_BODY\n\n### Links to Added Files:\n$LINKS"

        # Update the PR description using GitHub REST API
        curl -X PATCH \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
          -d "{\"body\": \"$UPDATED_BODY\"}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}